### ISSUE TITLE
ImportError: cannot import name ABC

### ISSUE THREAD

**Issue by maxcado** [karask/python-bitcoin-utils#1]
Hey, looks like a useful utility library  however upon installing and running the keys_addresses.py file here's the error:
Traceback (most recent call last):
 File "keys_addresses.py", line 14, in <module>
    from bitcoinutils.keys import P2pkhAddress, PrivateKey, PublicKey
File "/home/grace/.local/lib/python2.7/site-packages/bitcoinutils/keys.py", line 15, in <module>
     from abc import ABC, abstractmethod
ImportError: cannot import name ABC

**Comment by karask** [comment]
Hi @maxcado 

You don't provide much details on how you installed/tried it out but it seems like a versioning issue (e.g. using python 2.x).

I just tested locally (Ubuntu 16.04) by creating a virtual python3 environment.

Try:
$ mkdir testbitcoinutils
$ cd testbitcoinutils
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install bitcoin-utils
$ python path/to/keys_addresses.py

**Comment by karask** [comment]
Just tried with python 2.7 and I can confirm that this was the issue; it gives exactly the error you mentioned!
