### ISSUE TITLE
Small inconsistance in the documentation in current version

### ISSUE THREAD

**Issue by WenjianDong** [karask/python-bitcoin-utils#10]
Hello, 

Currently, there is a small inconsistance in the docstrings in the file python-bitcoin-utils/bitcoinutils/keys.py. Under the docstrings of the class PrivateKey, there is a function: 

    sign_transaction(tx, compressed=True)

But the function seems to have been changed as:

    sign_input(self, tx, txin_index, script, sighash=SIGHASH_ALL)

It is just a small inconsistency in the doc. The performance is good. Maybe updating the doc in the next version?

Thanks.

**Comment by karask** [comment]
Thanks, fixed.
