### ISSUE TITLE
There is a difference between the nodejs bitcoinjs signature text information and the python-bitcoin-utils signature text information

### ISSUE THREAD

**Issue by wyq000** [karask/python-bitcoin-utils#103]
The final length of the nodejs signature is 128 bits, why is the final length of the python-bitcoin-utils signature 130 bits? What causes this difference?

**Comment by karask** [comment]
Hi @wyq000 ,

The sizes of valid signatures can vary, even for the same txs. Are the txs you are comparing legacy or segwit/toproot?

Also, I always use bitcoin-core as reference (other libraries typically to the same). Iirc, there is only one case that bitcoin-utils' library produces different (valid!) signatures than bitcoin-core.

I could try to check this further if you provide the tx for me to check.

**Comment by karask** [comment]
Hi @wyq000 ,

Just back from holidays.

I need the signature as generated from bitcoin-utils and bitcoin-core. This is because bitcoin core is the only reference that I can use. E.g. I can investigate further if the signatures bitcoin-utils produces is different that bitcoin core.
