### ISSUE TITLE
Error when deserializing transaction

### ISSUE THREAD

**Issue by ramonamela** [karask/python-bitcoin-utils#107]
In bitcoinutils/transaction.py, line 589, the cursor gets updated even if n_items = 0. For some cases, size > 0 but n_items = 0. In this case, n_items should be prioritized and consider that the witness is empty.
This verification should be added to avoid incrementing the cursor incorrectly (and then loading a bad locktime since the cursor was increased incorrectly). This is being solved in this PR: https://github.com/karask/python-bitcoin-utils/pull/104/files

**Comment by ramonamela** [comment]
The problem is solved here: https://github.com/karask/python-bitcoin-utils/pull/100/files

**Comment by karask** [comment]
Yes, that was a past issue and was solved. I will close this for now but please let me know if you find more.

Thank you for your contributions.
