### ISSUE TITLE
Please allow some flexibility for dependency versions

### ISSUE THREAD

**Issue by comtom** [karask/python-bitcoin-utils#22]
For projects that depend on the libraries that bitconutils uses, it is very possible that there are conflicting dependencies causing the project to fail to install. With pip install usually it only prints a warning in the terminal, but if the main project uses pipenv or poetry such a conflict will prevent to install any dependency.

Reason of this issue is in setup.py. Instead of:
```
      install_requires=[
          'base58check==1.0.2',
          'ecdsa==0.17.0',
          'sympy==1.3',
          'python-bitcoinrpc==1.0'
      ],
```
can be
```
      install_requires=[
          'base58check>=1.0.0,<1.0.3',
          'ecdsa>=0.12.0,<0.18.0',
          'sympy>=1.2,<1.4',
          'python-bitcoinrpc>=1.0',<2.0
      ],
```

These ranges should be replaced too in requirements.txt

**Comment by karask** [comment]
I relaxed the requirements somewhat (for future upgrades mostly) except for ecdsa where I would need to test explicitly even for future versions.

If you have problems with a specific older version let me know and I will (test it first and) add it to the setup.py as required.

**Comment by comtom** [comment]
thanks, in my case I would need to relax ecdsa and sympy requirements a little bit. In general when there is a breaking change a library should increase their major version number. Although I understand that is still necessary to test, should be "safe" for most cases.

**Comment by karask** [comment]
The major version number wrt breaking changes does not apply to 0.x.x. That is actually where I had the problem previously (ecdsa).

I believe 'sympy>=1.2,<1.4' would be fine but in ecdsa I am afraid that I cannot even move it to 0.16 (although I will try if that would help).

I will not relax the requirements randomly. Please let me know exact version number and I will see if I can help.

**Comment by karask** [comment]
I noticed that I already did relax everything except ecdsa.

**Comment by comtom** [comment]
thanks I think is good for now. I'm closing this issue
