### ISSUE TITLE
redeem p2pkh adddress balance

### ISSUE THREAD

**Issue by fvdrummer2022** [karask/python-bitcoin-utils#30]
Hi I have a bitcoin address redeem script p2pkh, I don know how to go about redeeming the unspend balance from my address, I have read into the process, but still don/t understand, can send you my transaction   Fee
0.00019447 BTC
(70.206 sat/B - 25.388 sat/WU - 277 bytes)
(101.286 sat/vByte - 192 virtual bytes)
0.14669553 BTC
Hash
f0ff6231e0a9ba3fc5d0ae5f618850e0a57a161fd69007bfbdfba6e1c6b33e5c
2020-05-11 10:56
[3GmS7i3Pm8xA4Jb9fwYCbT7UkJWDuNiWAX](https://www.blockchain.com/btc/address/3GmS7i3Pm8xA4Jb9fwYCbT7UkJWDuNiWAX)
0.14689000 BTC
[bc1qk7h6nq2j4whztak03puk05t9zh85aup330gu4utal5n0d5k25usq0zwgh3](https://www.blockchain.com/btc/address/bc1qk7h6nq2j4whztak03puk05t9zh85aup330gu4utal5n0d5k25usq0zwgh3)
0.06567816 BTC
[1D97VBoikYqWzt29AZ3jXeYqstYnq1CyhJ](https://www.blockchain.com/btc/address/1D97VBoikYqWzt29AZ3jXeYqstYnq1CyhJ)
0.08101737 BTC
This transaction was first broadcast to the Bitcoin network on May 11, 2020 at 10:56 AM MST.  The transaction currently has 123,375 confirmations on the network.  At the time of this transaction, 0.14669553 BTC was sent with a value of $1,246.08. The current value of this transaction is now $3,133.21.  Learn more about [how transactions work](https://support.blockchain.com/hc/en-us/articles/360040028192-Anatomy-of-a-Bitcoin-Transaction).
Details
Hash
f0ff6231e0a9ba3fc5d0ae5f618850e0a57a161fd69007bfbdfba6e1c6b33e5c
Status
Confirmed
Received Time
2020-05-11 10:56
Size
277 bytes
Weight
766
Included in Block
[629993](https://www.blockchain.com/btc/block/629993)
Confirmations
123,375
Total Input
0.14689000 BTC
Total Output
0.14669553 BTC
Fees
0.00019447 BTC
Fee per byte
70.206 sat/B
Fee per vbyte
101.286 sat/vByte
Fee per weight unit
25.388 sat/WU
Value when transacted
$1,246.08
Inputs
HEX
ASM
Index
0
Details
[Output](https://www.blockchain.com/btc/tx/d4a056a60be14d0d13c8bf9a9e05f1f4e12d34c189b1ee79b9982174e01469ac)
Address
[3GmS7i3Pm8xA4Jb9fwYCbT7UkJWDuNiWAX](https://www.blockchain.com/btc/address/3GmS7i3Pm8xA4Jb9fwYCbT7UkJWDuNiWAX)
Value
0.14689000 BTC
Pkscript
OP_HASH160
a55fbed7d8fe42bb11b66f9ae9bfe9ebfcbe3dfa
OP_EQUAL
Sigscript
0020abde5e3877501ef34dcda0f42aa3f52673b395a866ad61f3660d2d036a7c5fc4
Witness
3044022001843fae362c47df2a1f678ae96c5c559c50ea2a110fd3dc2a0f8fd801afa0210220225e61b9d0340b516d54d454b838204fa9e34d75547f7e5a7b468eb6186fb9c501
5121035bef36265999cb6534ebfc7b54c334faaf50f54a2a46d89703f51468d9674e8551ae
Outputs
Index
0
Details
[Spent](https://www.blockchain.com/btc/tx/e6e77cc6540e5e49e2ce29eb542ebcfb5cabcddff118af6b9e0c01edb48819a2)
Address
[bc1qk7h6nq2j4whztak03puk05t9zh85aup330gu4utal5n0d5k25usq0zwgh3](https://www.blockchain.com/btc/address/bc1qk7h6nq2j4whztak03puk05t9zh85aup330gu4utal5n0d5k25usq0zwgh3)
Value
0.06567816 BTC
Pkscript
OP_0
b7afa98152abae25f6cf887967d16515cf4ef0318bd1caf17dfd26f6d2caa720
Index
1
Details
Unspent
Address
[1D97VBoikYqWzt29AZ3jXeYqstYnq1CyhJ](https://www.blockchain.com/btc/address/1D97VBoikYqWzt29AZ3jXeYqstYnq1CyhJ)
Value
0.08101737 BTC
Pkscript
OP_DUP
OP_HASH160
852a405633df80b64299a23284d9bf1ec7dd0d75
OP_EQUALVERIFY
OP_CHECKSIG

alternating coins
You’ve thought a

**Comment by karask** [comment]
I am having a lot of trouble understanding what the issue. An example of how to spend a P2PKH can be found here:

https://github.com/karask/python-bitcoin-utils/blob/master/examples/p2pkh_transaction.py
