### ISSUE TITLE
How to create P2PKH address

### ISSUE THREAD

**Issue by hasanparasteh** [karask/python-bitcoin-utils#35]
There are some examples but there's no explanation on how to create `P2PKH` address from public_key;  Here is the file you imported the class but it's not used!

https://github.com/karask/python-bitcoin-utils/blob/20b80acb91f2477a82d0245b760643011dc86a1b/examples/keys_addresses.py#L14

Please provide some information/examples to create these types of address..

thanks for considering and reading this issue

**Comment by karask** [comment]
Hi @hasanparasteh 

The P2PKH address is created in line 36 from the public key and stored to "address"; it is a P2pkhAddress object. In line 39 the base64encoding of the address is printed. 

Also see 

https://github.com/karask/python-bitcoin-utils/blob/20b80acb91f2477a82d0245b760643011dc86a1b/bitcoinutils/keys.py#L647
