### ISSUE TITLE
OverflowError: int too big to convert

### ISSUE THREAD

**Issue by tomjeannesson** [karask/python-bitcoin-utils#36]
Hello!
I'm am getting the following error when signing larger text messages (arround 600 characters), when testing my signatures with [this tool](https://reinproject.org/bitcoin-signature-tool/#sign).
```
message_size = len(message).to_bytes(1, byteorder='big')
OverflowError: int too big to convert
```
Is there a workaround to this (I am new to blockchain)?
Thanks for your time!

**Comment by tomjeannesson** [comment]
Shouldn't this be taken into account?
[Variable_length_integer](https://en.bitcoin.it/wiki/Protocol_documentation#Variable_length_integer)

**Comment by karask** [comment]
Hi @tomjeannesson 

Yes, it should be varint.  Just updated in 0.5.9.

Thanks for the feedback.

**Comment by tomjeannesson** [comment]
> Hi @tomjeannesson
> 
> Yes, it should be varint. Just updated in 0.5.9.
> 
> Thanks for the feedback.

Thanks for the quick fix!
