### ISSUE TITLE
Serializing a malformed transaction

### ISSUE THREAD

**Issue by msinkec** [karask/python-bitcoin-utils#39]
As mentioned in [this post](https://bitcoin.stackexchange.com/questions/118251/failing-to-construct-transaction-that-unlocks-p2wsh) using non-pushdata in a witness array causes the library to serialize a malformed transaction. Preferably it should throw an error upon serialization or maybe the witness API should be changed to not use `Script` objects.

```py
tx.witnesses.append(Script(['OP_5', 'OP_0', p2wsh_witness_script.to_hex()]))
```

**Comment by karask** [comment]
Thanks for letting me know. That requires cleanup. I have a 'create a TxInputWitness object' in the project's TODO list for quite some time now. I will prioritize this and it will be much cleaner that way. 

Is this a bottleneck for you?  Time is scarce and it might take a while.

**Comment by msinkec** [comment]
No worries, I can get around it. It's just a potential source of confusion.

**Comment by karask** [comment]
Done. A TxWitnessInput object is now passed instead of Script. All witness elements are (for now) expected as hex strings. See updated examples.

Pypi is not updated yet. I am delaying it to include other improvements.
