### ISSUE TITLE
binascii.Error: Odd-length string

### ISSUE THREAD

**Issue by iamnapo** [karask/python-bitcoin-utils#4]
Hello,

I think that [no padding necessary](https://github.com/karask/python-bitcoin-utils/blob/master/bitcoinutils/keys.py#L314) isn't always the case. An example is when trying to run [examples/spend_p2sh_csv_p2pkh.py](https://github.com/karask/python-bitcoin-utils/blob/master/examples/spend_p2sh_csv_p2pkh.py) with:
```python
txid = '9a11a2dfbf135bb1d3549ebfc09e29d485839ae879992170fd22d6fe7f1fd4a7'
vout = 1
```
By adding `.zfill(64)` to [keys.py#L315](https://github.com/karask/python-bitcoin-utils/blob/master/bitcoinutils/keys.py#L315), it seems to work fine. Please let me know if you need more information or if I'm doing something wrong.

**Comment by karask** [comment]
Thank you for reporting.

You get the error when you send the transaction to a node?

What error do you get exactly? 

I will look into it. (ideally a UTXO in testnet that will replicate it would be great!)

**Comment by iamnapo** [comment]
Hello again,

The error occurs when trying to use the script above, to just create the raw signed transaction. Should it matter if it's from a valid UTXO? (even though in my local regtest it is)
The full error when running the above is:
```python
Traceback (most recent call last):
  File "spend_p2sh_csv_p2pkh.py", line 81, in <module>
    main()
  File "spend_p2sh_csv_p2pkh.py", line 67, in main
    sig = p2pkh_sk.sign_input(tx, 0, redeem_script )
  File "/usr/local/lib/python3.6/site-packages/bitcoinutils/keys.py", line 315, in sign_input
    new_S = unhexlify( format(new_S_as_bigint, 'x') )
binascii.Error: Odd-length string
```

**Comment by karask** [comment]
I assumed the error was when you were sending it to a node... which is not uncommon given an invalid UTXO.

You are correct, if it happens during creation of the raw tx, the UTXO itself is irrelevant as long as the txid is proper hex (which it is). The padding does not matter while one works with numbers (e.g. line above) ...not sure how the comment ended up there.

The hex does need to be even so you are right. Good catch!

I will change and test tomorrow (run the existing tests, etc.).

**Comment by karask** [comment]
Great stuff. It fixes it as expected! Maybe you would like to make a pull request?  (otherwise, I will commit the change tomorrow)

Thanks!
