### ISSUE TITLE
Bug in creating HDWallet with mnemonic

### ISSUE THREAD

**Issue by josh-davis-vicinft** [karask/python-bitcoin-utils#40]
Line 50 in bitcoinutils/hdwallet.py should be `self.hdw.from_mnemonic(mnemonic=mnemonic)` instead of `self.hdw.from_xprivate_key(mnemonic=mnemonic)`.

**Comment by karask** [comment]
Thanks! Did a quick commit in master. I don't have much time now but I will soon commit a new release (that includes full taproot support) and I will add proper tests for hdwallet functionality there.
