### ISSUE TITLE
how I can find the correct UTXO Txid for transaction

### ISSUE THREAD

**Issue by MohsenHaydari** [karask/python-bitcoin-utils#42]
I am designing a Bitcoin wallet with ported this package to dart
I have somewhat figured out how to send a Bitcoin transaction with different address types and have sent several transactions, I would like to know how to find the UTXO transaction ID that matches the user's balance other than searching for Bitcoin blocks to match.
As I understand it, I need to find the UTXO transaction that has the same address type (P2pkh, Segwit, ...), and the UTXO transaction amount is greater than (send amount + fee) and less than the user's balance.
Thanks

**Comment by karask** [comment]
Hi Mohsen,

You typically get those from a bitcoin node or other software that keeps such data. You can use the proxy object to talk to your node. For example, see 'listunspent' bitcoin command.

You need to check the UTXO amounts programmatically and use as many as required to cover the amount you want to sent.

**Comment by MohsenHaydari** [comment]
> Hi Mohsen,
> 
> You typically get those from a bitcoin node or other software that keeps such data. You can use the proxy object to talk to your node. For example, see 'listunspent' bitcoin command.
> 
> You need to check the UTXO amounts programmatically and use as many as required to cover the amount you want to sent.

Hello, thank you very much.

I was able to find an API that would provide exactly the transactions I needed. [nownodes.io](url)

How can I calculate the transaction fee in different script types?
There are 2 methods to measure the transaction volume: `get_size `and `get_vsize`

If I understood correctly, I should multiply the value of `estimatesmartfee ` by the size of the transaction, which of these volumes should I use, in an article I read that for Segwit transactions, the Segwit volume is not calculated for fee

And the last question, do you have a plan to work on the Lightning Network?

Thanks

**Comment by karask** [comment]
Segwit txs get a discount... effectively they can be considered less bytes than legacy txs for purposes of calculating tx fees. For legacy txs you should use size, for segwit vsize.

If I have free time in the future I might work on adding Lightning Network support but currently there are no plans for this.
