### ISSUE TITLE
dart package

### ISSUE THREAD

**Issue by MohsenHaydari** [karask/python-bitcoin-utils#45]
Hi, thanks for answering all my questions.
I converted a lot of your package code to Dart [link](https://github.com/MohsenHaydari/bitcoin)
Can I give information about your package on the `README `and link it?
I want to publish the package in [pub.dev](https://pub.dev/). Are you okay with that?
Thanks

**Comment by karask** [comment]
Hi Mohsen,

Yes, please mention and link!

**Comment by MohsenHaydari** [comment]
> Hi Mohsen,
> 
> Yes, please mention and link!

Thank you so much, GL
