### ISSUE TITLE
How can I spend several utxo if one of them is P2tr?

### ISSUE THREAD

**Issue by MohsenHaydari** [karask/python-bitcoin-utils#47]
I have succeeded spend multiple UTXO with different script types in one transaction, but if there is P2tr in them, it will fail. ``` "non-mandatory-script-verify-flag (Invalid Schnorr signature)```
If possible, add some new Pt2r samples.

I want to add `Multi-Sig` functionality to my wallet to send and receive Bitcoin transactions
What I came up with, the user needs to create a `P2wsh ` address, to create this script, the user needs to add the public keys of the accounts they want to unlock the script with. The wallet generates a `p2wsh `address using the `p2wsh `script and public keys, the user gives the address of this script to the clients to receive the amount, and finally, the user can spend this script through the private key of the account. Is the method correct?

Is it possible to decode utxos script hash (p2wsh)  to find conditions? (how many signatures)

Thanks

**Comment by karask** [comment]
Example https://github.com/karask/python-bitcoin-utils/blob/master/examples/spend_multi_input_p2tr_and_p2pkh.py demonstrates how to spend both taproot and legacy UTXOs in one tx. 

Note that we add an empty witness that corresponds to the legacy utxo: tx.witnesses.append( TxWitnessInput([]) )

**Comment by MohsenHaydari** [comment]
> Example https://github.com/karask/python-bitcoin-utils/blob/master/examples/spend_multi_input_p2tr_and_p2pkh.py demonstrates how to spend both taproot and legacy UTXOs in one tx.
> 
> Note that we add an empty witness that corresponds to the legacy utxo: tx.witnesses.append( TxWitnessInput([]) )

I tried this method, and it worked great with P2PKH. However, when mixing it with P2WPKH or P2SH, I encountered the same error (RPCError: got code -26 with the message 'non-mandatory-script-verify-flag (Invalid Schnorr signature)'). Could you take a look at this code and help me identify the issue? 

The code is ready for broadcasting
```
def main():
    # always remember to setup the network
    setup('testnet')
    priv1 = PrivateKey("cV3R88re3AZSBnWhBBNdiCKTfwpMKkYYjdiR13HQzsU7zoRNX7JL")
    priv2 = PrivateKey("cSfna7riKJdNU7skpRUx17WYANNsyHTA2FmuzLpFzpp37xpytgob")
    pub1 = priv1.get_public_key()
    pub2 = priv2.get_public_key()
    fromAddress1 = pub1.get_taproot_address()
    fromAddress2 = pub2.get_address()
    # p2tr utxo
    txid1 = 'd18b272e110fadd753dc30e08e9b12c1effe58a4f1253ae2289248b2994d0bf8'
    vout1 = 0
    # P2wpkh UTXO
    txid2 = 'd18b272e110fadd753dc30e08e9b12c1effe58a4f1253ae2289248b2994d0bf8'
    vout2 = 1
    amount1 = 100000
    amount2 = 100000
    amounts = [amount1, amount2]
    script_pubkey1 = fromAddress1.to_script_pub_key()
    script_pubkey2 = fromAddress2.to_script_pub_key()
    utxos_script_pubkeys = [script_pubkey1, script_pubkey2]

    toAddress = P2pkhAddress('mnv5EAfPMTbfatz5ZbT6uUKpK7E5MftBAv')
    txin1 = TxInput(txid1, vout1)
    txin2 = TxInput(txid2, vout2)
    txOut = TxOutput(to_satoshis(0.0000022), toAddress.to_script_pub_key())

    tx = Transaction([txin1, txin2], [txOut], has_segwit=True)
    sig1 = priv1.sign_taproot_input(tx, 0, utxos_script_pubkeys, amounts)
    sig2 = priv2.sign_segwit_input(tx, 1, script=script_pubkey2, amount=amount1)

    tx.witnesses.append(TxWitnessInput([sig1]))
    tx.witnesses.append(TxWitnessInput([sig2, pub2.to_hex()]))
    print("\nRaw signed transaction:\n" + tx.serialize())
    # broadcast fail !
    # got error RPCError: got code -26 with msg "non-mandatory-script-verify-flag (Invalid Schnorr signature)".
    #
```

I apologize for the numerous questions I am asking you, and I appreciate your responses. If feasible, could you please assist me in creating a test transaction with a memo or note? I am sincerely grateful for your help.

**Comment by MohsenHaydari** [comment]
After conducting multiple tests without success, I reached the conclusion that the issue might reside with the node itself. It appears that the problem lies within the node. I managed to successfully send this transaction using a different node 

TX ids

```
88558b495f28ff4799a4dacf40ee5cd1666850fed4847b8315256a5ae22527f8
02429ffe2f82f587d8e7a6e925201d3e7f219ac3af3688f2bc5c2770204e5d5c

```
 However, none of these transactions have received confirmation. What do you think could be the reason for this?

**Comment by karask** [comment]
Bitcoin testnet is known to be quite unstable. If you notice there aren't new blocks from yesterday:

https://live.blockcypher.com/btc-testnet/

That is why signet was created; to provide a more stable env for testing. I use both and although testnet is less reliable it does the job just fine.
