### ISSUE TITLE
Spend P2SH Transaction | Not allowed | Reject-reason: missing-inputs

### ISSUE THREAD

**Issue by Deepanshu2017** [karask/python-bitcoin-utils#49]
Hello,

While attempting to execute the code provided in the [Spend P2SH Transaction](https://github.com/karask/python-bitcoin-utils/blob/master/examples/spend_p2sh_transaction.py) repository, I managed to successfully sign the transaction. However, I encountered an issue with the `testmempoolaccept` function, which resulted in a rejection due to "missing inputs."

Here are the details of the raw unsigned and signed transactions, as well as the associated transaction ID:

```
Raw unsigned transaction:
02000000015b940c0a5b932c1f8cea231248346f93f18865904e15cecc64bbfaa7d563b37d0000000000ffffffff0140548900000000001976a914fd337ad3bf81e086d96a68e1f8d6a0a510f8c24a88ac00000000

Raw signed transaction:
02000000015b940c0a5b932c1f8cea231248346f93f18865904e15cecc64bbfaa7d563b37d000000006d4830450221008681b499c4fe8c2ea62ab12bc5514e3e8a0d9edd1595348f291e00e7c36983ec022010dea656bcba4bb1dda081b5dd2ed2ff704ad00e17b4b0cef18e630bc901dde301232103a2fef1829e0742b89c218c51898d9e7cb9d51201ba2bf9d9e9214ebb6af32708acffffffff0140548900000000001976a914fd337ad3bf81e086d96a68e1f8d6a0a510f8c24a88ac00000000

TxId: 22ab0820ebc9999167ef2a34deff97721777f5e2582adadd5d5a142ddf18341b
```

Furthermore, the response from `testmempoolaccept` is as follows:

```
{'txid': '22ab0820ebc9999167ef2a34deff97721777f5e2582adadd5d5a142ddf18341b',
 'wtxid': '22ab0820ebc9999167ef2a34deff97721777f5e2582adadd5d5a142ddf18341b',
 'allowed': False,
 'reject-reason': 'missing-inputs'}
```

Feel free to let me know if you need any further assistance or clarification.

**Comment by karask** [comment]
Hi

If you go to an explorer you'll see that the input is already spent. That is why it is missing:
https://live.blockcypher.com/btc-testnet/tx/7db363d5a7fabb64ccce154e906588f1936f34481223ea8c1f2c935b0a0c945b/

Most, if not all, of the examples have spent transactions. Somebody, run the example directly (not with testmempoolaccept) and spent the tx.

You have to create your own UTXOs to test the examples. 

I am working on a book (https://github.com/karask/bitcoin-textbook -- find the .pdf) that may help you in further exploring Bitcoin.

I hope the above help.
