### ISSUE TITLE
is there any example of using OP_CHECKLOCKTIMEVERIFY ?

### ISSUE THREAD

**Issue by mohsenrahmanikivi** [karask/python-bitcoin-utils#51]
Hey there! I was looking for an example of how to use OP_CLTV, but couldn't find anything. However, I did come across your implementation of OP_CSV and found a great example for that. Do you think you could provide an example for OP_CLTV as well? I've heard that setting the flags can be tricky and I'm not sure how to do it. Thanks!

**Comment by karask** [comment]
Glad you found it! I don't have an example with CLTV because it is one of the assignments in the classes I give. :-)
