### ISSUE TITLE
Transaction from_raw function not encoding locktime or version

### ISSUE THREAD

**Issue by rramakrishnan246** [karask/python-bitcoin-utils#53]
As far as I can tell, when trying to convert an encoded hex string into the Transaction class via the from_raw() function, neither the locktime nor version is encoded into the Transaction object. The version is not as big of a deal since it can be easily guessed (but I think should be fixed), but the locktime is not encoded either. This has implications when being signed and hashed and will cause failures. 

Another minor point: the comments for the from_raw function for Transaction and TxOutput are copied from the TxInput (which is also slightly wrong):

`    @staticmethod
    def from_raw(rawtxhex: str):
        """
        Imports a Transaction from hexadecimal data

        Attributes
        ----------
        txinputraw : string (hex)
            The hexadecimal raw string of the Transaction
        cursor : int
            The cursor of which the algorithm will start to read the data
        has_segwit : boolean
            Is the Tx Input segwit or not
        """`

Can someone confirm if these are valid concerns or is a different function I should be using when having a consensus encoded txn hex string and converting it?

I can also make some PRs as well but not sure what is the preferred practice here

**Comment by karask** [comment]
Hi Rohan. Yes these should all be fixed. PRs will definitely be appreciated.
