### ISSUE TITLE
Schnorr signature not identical with BTC core

### ISSUE THREAD

**Issue by dingguijin** [karask/python-bitcoin-utils#56]
Actually, it is not an issue.

As the comments in the code keys.py

        # deterministic signing nonce is random and RFC6979-like
        # it is the hash of the tx_digest and private key
        # TODO not identical to Bitcoin Core's signature, rand_aux
        # needs to change if we want identical signatures!
        rand_aux = hashlib.sha256(tx_digest + byte_key).digest()

So how to make this identical with BTC Core.

**Comment by dingguijin** [comment]
Not issue.

**Comment by karask** [comment]
Hi @dingguijin 

As you said it is not that important but I would like it to be identical to Core. So this is a TODO for the long term.

Just have to spend some time figuring out exactly what kind of rand_aux Core is using and emulating it in the library's code.
