### ISSUE TITLE
Update Copyright in all Files 2018-2022

### ISSUE THREAD

**Issue by iamhardikat11** [karask/python-bitcoin-utils#80]
Hi @karask Do we have change the Copyright of all files as mentioned in the TODO File. If so, I will make a PR for the Same.

**Comment by iamhardikat11** [comment]
Then, I am thinking on working on the Test Suite, any suggestions for the same will be very appreciated.

**Comment by karask** [comment]
The Copyright is usually the original date of creation (2018) up to the current year (2024).

The copyright for the test suite would be the same.

For the test suite, we can increase testing coverage by adding new tests; testing existing methods that do not have a test already.

A more challenging task would be to improve the test suite similarly to the bitcoin-core project; effectively all the values would be in json files so we can add/remove tests easily. The tests would then use these json files. This requires a lot of thought to make properly.
