### ISSUE TITLE
Adding annex to signature hash

### ISSUE THREAD

**Issue by vking45** [karask/python-bitcoin-utils#84]
In the traditional Schnorr signature scheme, the verification process typically involves verifying the correctness of the signature with respect to the message and the public key of the signer. The annex value itself may not be directly involved in the verification process, as it is often considered as additional data that does not affect the validity of the signature.

@karask do we need to consider annex in the verification process ?

**Comment by karask** [comment]
If I remember correctly annex is not used yet. When it is used then it will be part of the digest to sign. I have left this implementation for later since I wasn't sure of the use cases that it applies.

Not sure if I answered your question :)

**Comment by vking45** [comment]
You sort of answered it, for now I think we should leave annex out of the signatures, I will get back to this after gathering enough credible information about implementation which includes annexes.
