### ISSUE TITLE
Doubt in TODO: TxWitnessInput/Script can take objects and call the appr. method to hexlify after inspecting the obj

### ISSUE THREAD

**Issue by iamhardikat11** [karask/python-bitcoin-utils#90]
My Question is that when we create a object for TxWitnessInput/Script class, we need lists as inputs for both of them, so do you wish for all the items of the list to made into hex, like by using to_hex().

**Comment by karask** [comment]
Hi @iamhardikat11 

Please ignore this TODO. I will remove it. The rationale was to simplify calling the class but I'd rather users explicitly put the proper values there.
