### ISSUE TITLE
TODO Task: SHORT TERM Check and fix potential vulnerabilities:

### ISSUE THREAD

**Issue by iamhardikat11** [karask/python-bitcoin-utils#92]
Check and fix potential vulnerabilities: [Link](https://github.com/karask/python-bitcoin-utils/security/dependabot) is non-existent, so please clarify whether or not is a Active Task or Not.

**Comment by karask** [comment]
Hi @iamhardikat11

https://github.com/karask/python-bitcoin-utils/security/dependabot/2

I just did a quick investigation and the library will not solve minerva timing attacks. This is a difficult task and I will update the TODO accordingly.
